[package]
name = "ft_linear_regression"
version = "0.1.0"
edition = "2024"
default-run = "estimate"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
pest = "2.8.2"
pest_derive = "2.8.2"
plotters = "0.3.7"
